#!/usr/bin/env ruby

require 'rake'
require 'json'
require 'optparse'

URLS = []
JMETER_FILE = 'jmeter.rb'

task :run do |t, args|
  options = {
    host: 'http://localhost:10003',
    number: 10,
    file: '',
  }

  o = OptionParser.new

  o.banner = "Usage: rake run [options]"
  o.on('-h HOST', '--host HOST') { |host|
    options[:host] = host
  }

  o.on('-n NUMBER', '--n NUMBER') { |number|
    options[:number] = number
  }

  o.on('-f FILE', '--f FILE') { |file|
    options[:file] = file
  }

  # return `ARGV` with the intended arguments
  args = o.order!(ARGV) {}

  o.parse!(args)

  puts options

  Rake::Task['lograge'].invoke(options[:file], options[:host])
  Rake::Task['generate_jmeter'].invoke(options[:number], options[:host])

  puts 'Running jmeter.rb file...'
  Kernel.exec "ruby #{JMETER_FILE}"
end

task :lograge, [:file, :host] do |t, args|
  puts "Parsing lograge to generate url..#{args}"
  unless FileTest.file?("./#{args[:file]}")
    abort("rake aborted: '#{args[:file]}' file not found.")
  end

  File.readlines(args[:file]).each do |line|
    path = (JSON.parse line)['path']
    URLS << "#{args[:host]}#{path}"
  end
  puts "Generated urls: #{URLS.length}"
end

task :generate_jmeter, [:number, :host] do |t, args|
  puts args[:host]
  File.open(JMETER_FILE, 'w') do |file|
    file.puts "#!/usr/bin/env ruby"
    file.puts "require 'ruby-jmeter'"
    file.puts 'test do'
      file.puts "threads count: #{args[:number]}  do"
      file.puts 'think_time 5000, 2000'

      login_params = {
        user_session: {
          email: "sarahkim@factual.com",
          password: "temp123"
        }
      }

      file.puts <<-eos
        header({
          name: 'Content-Type', value: 'application/json; text/html; charset=utf-8'
        })

        post name: 'Log in',
          url: '#{args[:host]}/login',
          raw_body: #{login_params}.to_json
      eos

      URLS.each do |url|
       file.puts "visit name: '#{url}', url: '#{url}'"
      end

      file.puts 'end'
      file.puts 'view_results_tree'
      file.puts 'summary_report'
    file.puts 'end.run(gui: true)'
  end
end
